baseURL = 'https://l-lu-u.github.io/'
languageCode = 'en-us'
hasCJKLanguage = true
author = "Lu"
copyright = "Copyright © Lù 2024"
disqusShortname = "LU"
enableInlineShortcodes = true
title = 'lù, portfolio'